In [2]:
import pandas as pd
import numpy as np

In [3]:
df2023 = pd.read_csv('../data/train_metadata2023.csv')

In [4]:
df2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16941 entries, 0 to 16940
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   primary_label     16941 non-null  object
 1   secondary_labels  16941 non-null  object
 2   type              16941 non-null  object
 3   latitude          16714 non-null  float64
 4   longitude         16714 non-null  float64
 5   scientific_name   16941 non-null  object
 6   common_name       16941 non-null  object
 7   author            16941 non-null  object
 8   license           16941 non-null  object
 9   rating            16941 non-null  float64
 10  url               16941 non-null  object
 11  filename          16941 non-null  object
dtypes: float64(3), object(9)
memory usage: 1.6+ MB

In [5]:
dfRedlist = pd.read_csv('../data/finally_bird_list.csv')

In [6]:
dfRedlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   common_name      81 non-null     object
 1   count            81 non-null     int64
 2   scientific_name  81 non-null     object
 3   primary_label    81 non-null     object
 4   Red List Status  81 non-null     object
dtypes: int64(1), object(4)
memory usage: 3.3+ KB

In [7]:
# Merge dfRedlist with df2023 on the 'scientific_name' column
df2023 = df2023.merge(dfRedlist[['scientific_name', 'Red List Status']], on='scientific_name', how='left')

# Display the first few rows to verify the merge
df2023.head()

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,author,license,rating,url,filename,Red List Status
0,abethr1,[],['song'],4.3906,38.2788,Turdus tephronotus,African Bare-eyed Thrush,Rolf A. de By,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://www.xeno-canto.org/128013,abethr1/XC128013.ogg,NaN
1,abethr1,[],['call'],-2.9524,38.2921,Turdus tephronotus,African Bare-eyed Thrush,James Bradley,Creative Commons Attribution-NonCommercial-Sha...,3.5,https://www.xeno-canto.org/363501,abethr1/XC363501.ogg,NaN
2,abethr1,[],['song'],-2.9524,38.2921,Turdus tephronotus,African Bare-eyed Thrush,James Bradley,Creative Commons Attribution-NonCommercial-Sha...,3.5,https://www.xeno-canto.org/363502,abethr1/XC363502.ogg,NaN
3,abethr1,[],['song'],-2.9524,38.2921,Turdus tephronotus,African Bare-eyed Thrush,James Bradley,Creative Commons Attribution-NonCommercial-Sha...,5.0,https://www.xeno-canto.org/363503,abethr1/XC363503.ogg,NaN
4,abethr1,[],"['call', 'song']",-2.9524,38.2921,Turdus tephronotus,African Bare-eyed Thrush,James Bradley,Creative Commons Attribution-NonCommercial-Sha...,4.5,https://www.xeno-canto.org/363504,abethr1/XC363504.ogg,NaN

In [10]:
df2023['Red List Status'].nunique()

0

In [ ]:
import glob

# Beispiel: Dateien im Ordner einer Spezies auflisten
species_folder = os.path.join(spectrograms_path, df.iloc[0]['primary_label'])
print(glob.glob(os.path.join(species_folder, "*.png")))

In [11]:
import pandas as pd
import numpy as np

In [14]:
df =pd.read_csv('../Spectogram/basemodel_list.csv')
df.head()

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,date,filename,time,geometry,Red List Status
0,banswa,[],['call'],54.5592,11.9695,Riparia riparia,Bank Swallow,2013-06-08,XC138517.png,05:18,POINT (11.9695 54.5592),LC
1,banswa,[],"['alarm call', 'call']",46.1374,5.9609,Riparia riparia,Bank Swallow,2013-07-13,XC142649.png,09:00,POINT (5.9609 46.1374),LC
2,banswa,[],"['alarm call', 'call']",46.1374,5.9609,Riparia riparia,Bank Swallow,2013-07-13,XC142650.png,09:00,POINT (5.9609 46.1374),LC
3,banswa,[],"['male', 'song']",51.4028,22.1167,Riparia riparia,Bank Swallow,2014-06-28,XC184471.png,12:00,POINT (22.1167 51.4028),LC
4,banswa,[],['flight call'],52.3362,13.8090,Riparia riparia,Bank Swallow,2014-08-10,XC190292.png,06:40,POINT (13.809 52.3362),LC

In [30]:
df[df['primary_label'] == 'woosan']

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,date,filename,time,geometry,Red List Status
14274,woosan,['eaywag1'],['call'],58.2887,14.0501,Tringa glareola,Wood Sandpiper,NaN,woosan/XC110316.png,NaN,POINT (14.0501 58.2887),LC
14275,woosan,[],"['call', 'song']",53.2770,22.6020,Tringa glareola,Wood Sandpiper,NaN,woosan/XC133322.png,NaN,POINT (22.602 53.277),LC
14276,woosan,[],"['alarm call', 'flight call']",43.4238,-0.4616,Tringa glareola,Wood Sandpiper,NaN,woosan/XC140651.png,NaN,POINT (-0.4616 43.4238),LC
14277,woosan,['eubeat1'],['flight call'],39.7018,16.5192,Tringa glareola,Wood Sandpiper,NaN,woosan/XC144919.png,NaN,POINT (16.5192 39.7018),LC
14278,woosan,[],['call'],43.4238,-0.4616,Tringa glareola,Wood Sandpiper,NaN,woosan/XC146063.png,NaN,POINT (-0.4616 43.4238),LC
...,...,...,...,...,...,...,...,...,...,...,...,...
25138,woosan,[],[''],39.3840,16.5233,Tringa glareola,Wood Sandpiper,NaN,woosan/XC841723.png,NaN,POINT (16.5233 39.384),LC
25139,woosan,[],[''],43.6207,3.8725,Tringa glareola,Wood Sandpiper,NaN,woosan/XC846041.png,NaN,POINT (3.8725 43.6207),LC
25140,woosan,[],[''],43.6207,3.8725,Tringa glareola,Wood Sandpiper,NaN,woosan/XC856276.png,NaN,POINT (3.8725 43.6207),LC
25141,woosan,[],[''],49.2745,-0.2158,Tringa glareola,Wood Sandpiper,NaN,woosan/XC857968.png,NaN,POINT (-0.2158 49.2745),LC
25142,woosan,[],[''],49.2745,-0.2158,Tringa glareola,Wood Sandpiper,NaN,woosan/XC857970.png,NaN,POINT (-0.2158 49.2745),LC